ENHANCEMENT_TEXT = {
    "en": {
        "phase_short": "Phase {number}",
        "forecast_band": "Forecast range",
        "target_weekly_run_rate": "Target weekly run rate",
        "model_change": "Since last update",
        "baseline_model": "Baseline created",
        "target_gap": "Target gap",
        "target_not_set_short": "No target set",
        "update_model": "Apply changes",
        "pending_model_changes": "Unapplied changes. The dashboard still shows the last applied plan.",
        "model_change_value": "GMV {gmv} · Profit {profit}",
        "target_gap_value": "GMV {gmv} · Profit {profit}",
        "forecast_chart_caption": "Phase bands show weekly GMV against total cost. The shaded corridor reflects input confidence; a target line shows the average weekly run rate required to reach the plan target.",
        "weekly_profit_caption": "Weekly profit versus growth investment.",
        "cumulative_profit_caption": "Cumulative profit versus upfront investment. A target line appears when a profit target is set.",
        "funnel_business_lens": "Business lens. {samples} samples scale into {videos} videos, {clicks} clicks, and {orders} orders.",
        "channel_business_lens": "Business lens. This view keeps only two channels: Affiliate Video GMV and Store/Search GMV.",
        "cost_business_lens": "Business lens. The largest cost driver is {driver}; margin work should start there.",
        "executive_brief_investment": "{total} total, including {samples} for samples and {ads} for ads.",
        "executive_brief_sample": "Each sample contributes about {gmv} GMV and {profit} profit.",
        "executive_brief_diagnosis": "The largest GMV driver is {channel}. Weekly break-even: {weekly_be}. Cumulative break-even: {cumulative_be}. Main cost driver: {driver}.",
    },
    "zh": {
        "phase_short": "阶段 {number}",
        "forecast_band": "预测区间",
        "target_weekly_run_rate": "目标周均 GMV",
        "model_change": "较上次更新",
        "baseline_model": "已建立模型基线",
        "target_gap": "目标差距",
        "target_not_set_short": "未设置目标",
        "update_model": "应用更改并更新模型",
        "pending_model_changes": "存在尚未应用的更改，当前看板仍显示上一次确认的方案。",
        "model_change_value": "GMV {gmv} · 利润 {profit}",
        "target_gap_value": "GMV {gmv} · 利润 {profit}",
        "forecast_chart_caption": "阶段背景展示每周 GMV 与总成本。阴影区间反映输入可信度；设置 GMV 目标后，虚线表示达成目标所需的周均 GMV。",
        "weekly_profit_caption": "单周利润与增长投入。",
        "cumulative_profit_caption": "累计利润与前期投入；设置利润目标后会显示目标线。",
        "funnel_business_lens": "商业视角。{samples} 个样品预计带来 {videos} 条视频、{clicks} 次点击和 {orders} 个订单。",
        "channel_business_lens": "商业视角。这里只看两条渠道：达人视频 GMV 和店铺/Search GMV。",
        "cost_business_lens": "商业视角。当前最大成本项是 {driver}，利润优化应先看这一项。",
        "executive_brief_investment": "总增长投入 {total}，其中样品 {samples}，广告 {ads}。",
        "executive_brief_sample": "单个样品平均带来 {gmv} GMV 和 {profit} 利润。",
        "executive_brief_diagnosis": "当前最大 GMV 驱动来自 {channel}。单周回本：{weekly_be}；累计回本：{cumulative_be}。主要成本压力来自 {driver}。",
    },
    "de": {
        "phase_short": "Phase {number}",
        "forecast_band": "Prognosekorridor",
        "target_weekly_run_rate": "Wöchentlicher Zielwert",
        "model_change": "Seit letzter Aktualisierung",
        "baseline_model": "Basis erstellt",
        "target_gap": "Ziellücke",
        "target_not_set_short": "Kein Ziel festgelegt",
        "update_model": "Änderungen anwenden",
        "pending_model_changes": "Nicht angewendete Änderungen. Das Dashboard zeigt weiterhin den zuletzt bestätigten Plan.",
        "model_change_value": "GMV {gmv} · Gewinn {profit}",
        "target_gap_value": "GMV {gmv} · Gewinn {profit}",
        "forecast_chart_caption": "Die Phasen zeigen den wöchentlichen GMV im Vergleich zu den Gesamtkosten. Der Korridor spiegelt die Eingabesicherheit wider; die Ziellinie zeigt den erforderlichen durchschnittlichen Wochen-GMV.",
        "weekly_profit_caption": "Wöchentlicher Gewinn im Vergleich zur Wachstumsinvestition.",
        "cumulative_profit_caption": "Kumulierter Gewinn im Vergleich zur Vorabinvestition. Bei gesetztem Gewinnziel wird eine Ziellinie angezeigt.",
        "funnel_business_lens": "Business-Sicht. {samples} Samples entwickeln sich zu {videos} Videos, {clicks} Klicks und {orders} Bestellungen.",
        "channel_business_lens": "Business-Sicht. Diese Ansicht zeigt nur Affiliate-Video-GMV und Store/Search-GMV.",
        "cost_business_lens": "Business-Sicht. Der größte Kostentreiber ist {driver}; dort sollte die Margenoptimierung beginnen.",
        "executive_brief_investment": "Insgesamt {total}, davon {samples} für Samples und {ads} für Ads.",
        "executive_brief_sample": "Jedes Sample trägt etwa {gmv} GMV und {profit} Gewinn bei.",
        "executive_brief_diagnosis": "Der größte GMV-Treiber ist {channel}. Wöchentlicher Break-even: {weekly_be}. Kumulierter Break-even: {cumulative_be}. Wichtigster Kostentreiber: {driver}.",
    },
    "nl": {
        "phase_short": "Fase {number}",
        "forecast_band": "Prognoseband",
        "target_weekly_run_rate": "Wekelijkse doelwaarde",
        "model_change": "Sinds laatste update",
        "baseline_model": "Basis vastgelegd",
        "target_gap": "Doelverschil",
        "target_not_set_short": "Geen doel ingesteld",
        "update_model": "Wijzigingen toepassen",
        "pending_model_changes": "Niet-toegepaste wijzigingen. Het dashboard toont nog het laatst bevestigde plan.",
        "model_change_value": "GMV {gmv} · Winst {profit}",
        "target_gap_value": "GMV {gmv} · Winst {profit}",
        "forecast_chart_caption": "De fasen tonen wekelijkse GMV tegenover totale kosten. De band weerspiegelt de betrouwbaarheid van de inputs; de doellijn toont de benodigde gemiddelde wekelijkse GMV.",
        "weekly_profit_caption": "Wekelijkse winst tegenover groei-investering.",
        "cumulative_profit_caption": "Cumulatieve winst tegenover de investering vooraf. Bij een winstdoel verschijnt een doellijn.",
        "funnel_business_lens": "Businessblik. {samples} samples groeien uit tot {videos} video's, {clicks} clicks en {orders} orders.",
        "channel_business_lens": "Businessblik. Deze weergave toont alleen Affiliate Video GMV en Store/Search GMV.",
        "cost_business_lens": "Businessblik. De grootste kostendrijver is {driver}; begin daar met margeoptimalisatie.",
        "executive_brief_investment": "In totaal {total}, waarvan {samples} voor samples en {ads} voor ads.",
        "executive_brief_sample": "Elk sample draagt ongeveer {gmv} GMV en {profit} winst bij.",
        "executive_brief_diagnosis": "De grootste GMV-driver is {channel}. Wekelijkse break-even: {weekly_be}. Cumulatieve break-even: {cumulative_be}. Belangrijkste kostendrijver: {driver}.",
    },
}
